// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-services.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var SERVICES = [
  { id: "residential", name: "Nettoyage R\xE9sidentiel", description: "Appartements, maisons et villas.", from_fcfa: 25e3 },
  { id: "commercial", name: "Nettoyage Commercial", description: "Bureaux, boutiques et immeubles.", from_fcfa: 5e4 },
  { id: "post_construction", name: "Nettoyage Apr\xE8s Construction", description: "Nettoyage complet apr\xE8s travaux.", from_fcfa: 45e3 },
  { id: "car_wash", name: "Lavage Auto", description: "Int\xE9rieur et ext\xE9rieur.", from_fcfa: 5e3 },
  { id: "carpet", name: "Nettoyage de Tapis & Moquettes", description: "Traitement en profondeur.", from_fcfa: 15e3 },
  { id: "windows", name: "Lavage de Vitres", description: "Vitres int\xE9rieures et ext\xE9rieures.", from_fcfa: 1e4 },
  { id: "deep_clean", name: "Nettoyage Approfondi", description: "Grand nettoyage saisonnier.", from_fcfa: 45e3 }
];
var list_services_default = defineTool({
  name: "list_services",
  title: "List cleaning services",
  description: "List LaFriend's Services cleaning offerings with indicative starting prices in FCFA.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(SERVICES, null, 2) }],
    structuredContent: { services: SERVICES }
  })
});

// src/lib/mcp/tools/get-business-info.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var INFO = {
  name: "LaFriend's Services M\xE9nagers",
  location: "Bafoussam, Cameroun",
  hours: "Lundi\u2013Samedi, 07:00\u201319:00",
  phone: "+237 693 13 82 92 / +237 683 40 62 90",
  email: "lafriendsservices@gmail.com",
  website: "https://lafriendsservices.lovable.app",
  languages: ["fr", "en"]
};
var get_business_info_default = defineTool2({
  name: "get_business_info",
  title: "Get business info",
  description: "Return LaFriend's Services contact details, hours, and location.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(INFO, null, 2) }],
    structuredContent: INFO
  })
});

// src/lib/mcp/tools/list-my-bookings.ts
import { createClient } from "npm:@supabase/supabase-js@^2.101.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.3.6";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_bookings_default = defineTool3({
  name: "list_my_bookings",
  title: "List my bookings",
  description: "List bookings owned by the signed-in LaFriend's Services customer.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Max rows to return (default 20).")
  },
  annotations: { readOnlyHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("bookings").select("id, service_type, status, preferred_date, preferred_time, address, full_name, created_at").eq("user_id", ctx.getUserId()).order("preferred_date", { ascending: false }).limit(limit ?? 20);
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { bookings: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ggsvvtzviwxpbjsnpzdv";
var mcp_default = defineMcp({
  name: "lafriends-services-mcp",
  title: "LaFriend's Services",
  version: "0.1.0",
  instructions: "Tools for LaFriend's Services M\xE9nagers (Bafoussam, Cameroun). Use `list_services` and `get_business_info` for public catalog/contact info. Use `list_my_bookings` to fetch the signed-in customer's cleaning bookings.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_services_default, get_business_info_default, list_my_bookings_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
